name = "facturino-dashboard"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2024-08-09"

[env.production]
route = "app.facturino.mx/*"
zone_id = ""

[assets]
directory = "web"
